name: Deploy
run-name: ${{ github.actor }} triggered this action.
on:
  push:
    branches: [main, dev]
jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux, ARM64]
    env:
      PATH: ${{ secrets.DEPLOY_PATH }}
    defaults:
      run:
        shell: bash
        # working-directory: ${{ env.PATH }}
    steps:
      - id: add_path
        run: echo "/usr/bin" >> $GITHUB_PATH
      - id: execute_sh
        run: |
          cd ${{ env.PATH }}
          ./deploy.sh ${{ github.ref_name }}
