name: Deploy
run-name: ${{ github.actor }} triggered this action.
on:
  push:
    branches: [main, dev]
jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux, ARM64]
    env:
      PATH: ${{ secrets.DEPLOY_PATH }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.PATH }}
    steps:
      - run: echo "/usr/bin" >> $GITHUB_PATH
      - run: chmod u+x ./deploy.sh
      - run: ./deploy.sh ${{ github.ref_name }}
