name: Deploy
run-name: ${{ github.actor }} triggered this action.
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux, ARM64]
    env:
      PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - run: cd $PATH
      - uses: actions/checkout@v3.3.0
      - run: chmod u+x ./deploy.sh
      - run: ./deploy.sh
