name: Deploy
run-name: ${{ github.actor }} triggered this action.
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux, ARM64]
    env:
      PATH: ${{ secrets.DEPLOY_PATH }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.PATH }}
    steps:
      - run: pwd
      - run: git reset --hard
      - run: git checkout $GITHUB_REF_NAME
      - run: git fetch
      - run: chmod u+x ./deploy.sh
      - run: ./deploy.sh
