name: Deploy
run-name: ${{ github.actor }} triggered this action.
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux, ARM64]
    env:
      PATH: ${{ secrets.DEPLOY_PATH }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Execute
        run: |
          cd $PATH
          pwd
          git reset --hard
          git checkout $GITHUB_REF_NAME
          git fetch
          chmod u+x ./deploy.sh
          ./deploy.sh
