name: Main Tracker
run-name: ${{ github.actor }} triggered this action.
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux]
    steps:
      - name: Fetch
        shell: bash
        run: |
          cd /var/www/naru-aviation-web
          git reset --hard
          git checkout main
          git pull
      - name: Build
        shell: bash
        run: |
          cd /var/www/naru-aviation-web
          npm run build
