name: Main Tracker
run-name: ${{ github.actor }} triggered this action.
on:
  push:
    branches:
      - main
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch upstream
        shell: bash
        run: |
          git reset --hard
          git checkout main
          git pull
