name: Main Tracker
run-name: ${{ github.actor }} triggered this action.
on:
  push:
    branches:
      - main
jobs:
  fetch:
    name: Fetch
    runs-on: [self-hosted, linux]
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v3
      #  with:
      #    ref: main
      #    fetch-depth: 0
      - name: Fetch upstream
        shell: bash
        run: |
          cd /var/www/naru-aviation-web
          git reset --hard
          git checkout main
          git pull
